<?php

namespace CRTravelBundle\Repository;

/**
 * HotWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotWordRepository extends \Doctrine\ORM\EntityRepository
{
}
