<?php

namespace CRTravelBundle\Repository;

/**
 * PartnerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
