<?php

namespace CRTravelBundle\Repository;

/**
 * PartnerRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
